Study/Controllers/HomeController.cs
using Study.Persistence;
using Study.Persistence.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Study.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var studentRepository = new StudentRepository();
            var students = studentRepository.GetAll();
            ViewBag.Students = students;

            var courseRepository = new CourseRepository();
            var courses = courseRepository.GetAll();
            ViewBag.Courses = courses;

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Study/Controllers/StudentController.cs
using Study.Persistence;
using Study.Persistence.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Study.Controllers
{
    public class StudentController : Controller
    {
        public ActionResult List()
        {
            var studentRepository = new StudentRepository();
            var students = studentRepository.GetAll();
            ViewBag.Students = students;
            return View();
        }

        public ActionResult Card(int id)
        {
            var studentRepository = new StudentRepository();
            var student = studentRepository.GetById(id);
            ViewBag.Student = student;
            return View();
        }
    }
}

Study/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Study/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Study/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Studenti</h1>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Studenti</h2>
        <table>
            <tr>
                <td>ID</td>
                <td>Name</td>
            </tr>
            @foreach (var student in ViewBag.Students)
            {
            <tr>
                <td>@student.Id</td>
                <td>@student.Name</td>
            </tr>
            }
        </table>
        <p class="btn btn-default" >@Html.ActionLink("Svi", "List", "Student")</p>
    </div>
    <div class="col-md-6">
        <h2>Kolegiji</h2>
        <table>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Description</td>
            </tr>
            @foreach (var course in ViewBag.Courses)
            {
                <tr>
                    <td>@course.Id</td>
                    <td>@course.Name</td>
                    <td>@course.Description</td>
                </tr>
            }
        </table>
    </div>
</div>

Study/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Studenti", "List", "Student")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Study/Views/Student/Card.cshtml
@{
    ViewBag.Title = $"Student" + ViewBag.Student.Name;
}

<div class="jumbotron">
    <h1>Student @ViewBag.Student.Name</h1>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-2">
                Id
            </div>
            <div class="col-md-10">
                <span id="Id">@ViewBag.Student.Id</span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                Name
            </div>
            <div class="col-md-10">
                <input id="Name" value="@ViewBag.Student.Name" />
            </div>
        </div>
    </div>
</div>

Study/Views/Student/List.cshtml
@{
    ViewBag.Title = "Studenti";
}

<div class="jumbotron">
    <h1>Studenti</h1>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>Studenti</h2>
        <table>
            <tr>
                <td>ID</td>
                <td>Name</td>
            </tr>
            @foreach (var student in ViewBag.Students)
            {
            <tr>
                <td>@student.Id</td>
                <td>@student.Name</td>
                <td>@Html.ActionLink("Uredi", $"Card/{student.Id}", "Student")</td>
            </tr>
            }
        </table>
    </div>
</div>